name: WarpMenusReku
version: '1.0-SNAPSHOT'
main: me.rekuseq.warpmenusreku.WarpMenusReku
api-version: 1.19
authors: [ Rekuseq ]
description: warpy w gui



commands:
  warplist:
    description: Wydaje liste z warpami
    aliases: [warps, wp]

permissions:
  warplist.*:
    default: false
    children:
      warplist.warplistcommand: true
  warplist.warplistcommand:
    default: true